[package]
name = "db-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "db"            # This will produce a binary named `db`
path = "src/main.rs"   # Points to your main file

[dependencies]
anyhow = "1.0"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.4"
